---
- name: ensure systemd service
  notify: restart service pgscv-exporter
  copy:
    dest: /etc/systemd/system/pgscv-exporter.service
    mode: 0644
    content: |
      [Unit]
      Requires=docker.service
      After=docker.service
      StartLimitIntervalSec=0
      [Service]
      ExecStartPre=-/usr/bin/docker rm --force %N
      ExecStart=/usr/bin/docker run \
        --name=%N \
        --rm=true \
        --network=host \
        --stop-timeout=30 \
        --env=PGSCV_LISTEN_ADDRESS={{ pgscv_listen_address }} \
      {% if pgscv_exporter_disable_collectors is defined %}
        --env=PGSCV_DISABLE_COLLECTORS="{{ pgscv_exporter_disable_collectors }}" \
      {% endif %}
      {% if pgscv_exporter_database_dsn is defined %}
        --env=DATABASE_DSN="{{ pgscv_exporter_database_dsn }}" \
      {% endif %}
      {% if pgscv_exporter_pgbouncer_dsn is defined %}
        --env=PGBOUNCER_DSN="{{ pgscv_exporter_pgbouncer_dsn }}" \
      {% endif %}
        weaponry/pgscv:{{ pgscv_docker_image_tag }}
      ExecStop=-/usr/bin/docker stop %N
      Restart=always
      RestartSec=10
      KillMode=process
      [Install]
      WantedBy=multi-user.target

- name: ensure pgscv-exporter service is started
  systemd:
    name: pgscv-exporter
    daemon_reload: yes
    enabled: yes
    state: started
